# Generated by Django 4.2.23 on 2025-06-27 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField()),
                ('analyzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ems_app.analyzer')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ems_app.gateways')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ems_app.metadata')),
            ],
        ),
    ]
